version: '3'
services:
  nextjs:
    container_name: nextjs
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/nextjs-blog
      # exclude volumes
      - /nextjs-blog/node_modules
    tty: true
    stdin_open: true
